version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: weather_password
      MYSQL_DATABASE: weather_db_a
      MYSQL_USER: weather_user
      MYSQL_PASSWORD: weather_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
